<!DOCTYPE html>
<html>
<body>
	<div id="container">
         <div id="main">
        <h1>TERMS AND CONDITIONS</h1>
    The software products made available through the Mac App Store and App Store (collectively, the &ldquo;App Store Products&rdquo;) are licensed, not sold, to you. There are two (2) categories of App Store Products, as follows: (i) those App Store Products that have been developed, and are licensed to you, by Apple (&ldquo;Apple Products&rdquo;); and (ii) those App Store Products that have been developed, and are licensed to you, by a third-party developer (&ldquo;Third-Party Products&rdquo;). The category of a particular App Store Product (Apple Product or Third-Party Product) is identified on the Mac App Store application or App Store application.</p>
<p>
    Your license to each App Store Product is subject to the Licensed Application End User License Agreement set forth below, and you agree that such terms will apply unless the App Store Product is covered by a valid end user license agreement entered into between you and the licensor of that App Store Product (the &ldquo;Application Provider&rdquo;), in which case the Application Provider&rsquo;s end user license agreement will apply to that App Store Product. The Application Provider reserves all rights in and to the App Store Product not expressly granted to you.</p>
<p>
    You acknowledge that the license to each Apple Product that you obtain through the App Store Services, as defined below, or you associate with your Account, is a binding agreement between you and Apple. You acknowledge that: you are acquiring the license to each Third-Party Product from the Application Provider; Apple is acting as agent for the Application Provider in providing each such Third-Party Product to you; and Apple is not a party to the license between you and the Application Provider with respect to that Third-Party Product. The Application Provider of each Third-Party Product is solely responsible for that Third-Party Product, the content therein, any warranties to the extent that such warranties have not been disclaimed, and any claims that you or any other party may have relating to that Third-Party Product.</p>
<p>
    You acknowledge and agree that Apple and its subsidiaries are third-party beneficiaries of the Licensed Application End User License Agreement or the Application Provider&rsquo;s end user license agreement, as the case may be, for each Third-Party Product. You also agree that, upon your acceptance of the terms and conditions of the license to any such Third-Party Product, Apple will have the right (and will be deemed to have accepted the right) to enforce such license against you as a third-party beneficiary thereof.</p>
<p>
    IN-APP PURCHASES</p>
<p>
    Certain App Store Products may include functionality that enables you to receive additional services, or licenses to additional functionality or content for use within the App Store Product (&quot;In App Purchases&quot;). In App Purchases that are consumed during the use of the App Store Product (for example, virtual ammunition) cannot be transferred among devices; can be downloaded only once; and after being downloaded, cannot be replaced. Once a consumable In App Purchase is acquired and received by you, Apple shall be without liability to you in the event of any loss, destruction, or damage. All In App Purchases are deemed App Store Products, and In App Purchases received within Third-Party Products are deemed Third-Party Products, and treated as such, for purposes of these terms and conditions.</p>
<p>
    You must authenticate to acquire In-App Purchases separately from any authentication to obtain App Store Products by entering your password when prompted, but once you have authenticated to obtain an In-App Purchase, you will be able to acquire additional In-App Purchases for fifteen minutes without re-entering your password. You can turn off the ability to acquire In-App Purchases on your iOS Device by following the steps outlined at <a href="http://support.apple.com/kb/HT4213">http://support.apple.com/kb/HT4213</a>.</p>
<p>
    IN-APP SUBSCRIPTIONS</p>
<p>
    Certain App Store Products may include functionality that enables you to acquire content on a subscription basis (&ldquo;In App Subscriptions&rdquo;). Paid In App Subscriptions are non-refundable. In App Subscriptions will automatically renew for the applicable time period you have selected, and, where applicable, your Account will be charged no more than 24-hours prior to the expiration of the current In App Subscription period. You may cancel automatic renewal of paid In App Subscriptions by selecting Manage App Subscriptions in your Account and selecting the subscription you want to modify. In the event of a price increase, the In App Subscription may continue at the new price upon prior notice to you unless you have cancelled automatic renewal. You may cancel free In App Subscriptions by deleting the App Store Product from your device. Certain paid In App Subscriptions may offer a free trial period prior to charging your Account. If you decide you do not want to purchase the In App Subscription, turn off auto-renewal in your Account settings during the free trial period. Certain In App Subscriptions may be designated as magazine and newspaper products. You should review additional information about the magazine and newspaper subscription offer at the point of sale within the App Store Product. We may ask for your permission to provide the name, email address and zip code listed in your Account to the Application Provider of such magazine and newspaper subscriptions so that the Application Provider can send you marketing messages about its own products in accordance with its publicly posted privacy policy. Once the Application Provider has this information, it will be treated in accordance with the Application Provider&rsquo;s privacy policy. We encourage you to learn about the privacy practices of the Application Provider before agreeing to give it your personal information. For more information, please review the Application Provider&rsquo;s privacy policy or contact the Application Provider directly.</p>
<p>
    POPULAR NEAR ME</p>
<p>
    When you opt in to Popular Near Me via enabling Location Services, Apple will, from time to time, automatically collect information related to certain of your App Store Products, such as your time spent with each App Store Product and the number of times each App Store Product is launched. This information is stored anonymously and will not be associated with your name or Account. Apple will use this information, as well as other information, such as your App Store Product download history, to give personalized recommendations to you.</p>
<p>
    Apple may use this information and combine it with aggregated information from</p>
<p>
    other users who opt in to this feature, your iTunes Store purchase history data, your App Store download data, aggregated App Store Product download data from other users, and other information like customer ratings of App Store Products, to:</p>
<p>
    &bull; Provide you with recommendations regarding App Store Products, media, and other products and services that you may wish to purchase, download, or use.</p>
<p>
    &bull; Provide recommendations to other users.</p>
<p>
    At all times your information will be treated in accordance with Apple&rsquo;s Privacy Policy.</p>
<p>
    If you prefer that we do not collect and use information from your device or system in this manner, you should not enable Location Services or use Popular Near Me . You can opt out at any time by turning off Popular Near Me in the System Services menu of the Location Services settings on your device .</p>
<p>
    MAC APP STORE PRODUCT USAGE RULES</p>
<p>
    Except as otherwise set forth herein,</p>
<p>
    (i) If you are an individual acting in your personal capacity, you may download and use an application from the Mac App Store (&ldquo;Mac App Store Product&rdquo;) for personal, non-commercial use on any Apple-branded products running Mac OS X (&ldquo;Mac Computer&rdquo;) that you own or control.</p>
<p>
    (ii) If you are a commercial enterprise or educational institution, you may download a Mac App Store Product for use by either (a) a single individual on each of the Mac Computer(s) used by that individual that you own or control or (b) multiple individuals on a single shared Mac Computer that you own or control. For example, a single employee may use a Mac App Store Product on both the employee&rsquo;s desktop Mac Computer and laptop Mac Computer, or multiple students may serially use a Mac App Store Product on a single Mac Computer located at a resource center or library. For the sake of clarity, each Mac Computer used serially by multiple users requires a separate license.</p>
<p>
    (iii) Use may require sign-in with the Apple ID used to download the Mac App Store Product from the Mac App Store. Mac App Store Products can be updated through the Mac App Store only.</p>
<p>
    APP STORE AND APP STORE FOR APPLE TV PRODUCT USAGE RULES</p>
<p>
    (i) If you are an individual acting in your personal capacity, you may download and sync an App Store Product for personal, noncommercial use on any iOS or tvOS Device you own or control.</p>
<p>
    (ii) If you are a commercial enterprise or educational institution, you may download and sync an App Store Product for use by either (a) a single individual on one or more iOS or tvOS Devices used by that individual that you own or control or (b) multiple individuals, on a single shared iOS or tvOS Device you own or control. For example, a single employee may use an App Store Product on both the employee&#39;s iPhone and iPad, or multiple students may serially use an App Store Product on a single iPad located at a resource center or library. For the sake of clarity, each iOS or tvOS Device used serially or collectively by multiple users requires a separate license.</p>
<p>
    (iii) You shall be able to store App Store Products from up to five different Accounts at a time on a compatible iOS or tvOS Device.</p>
<p>
    (iv) You shall be able to manually sync App Store Products from at least one iTunes-authorized device to iOS Devices that have manual sync mode, provided that the App Store Product is associated with an Account on the primary iTunes-authorized device, where the primary iTunes-authorized device is the one that was first synced with the iOS Device or the one that you subsequently designate as primary using the iTunes application.</p>
<p>
    IMPORTANT SAFETY INFORMATION</p>
<p>
    To avoid muscle, joint, or eye strain during video game play, you should always take frequent breaks from playing, and take a longer rest if you experience any soreness, fatigue, or discomfort. A very small percentage of people may experience seizures or blackouts when exposed to flashing lights or patterns, including while playing video games or watching videos. Symptoms may include dizziness, nausea, involuntary movements, loss of awareness, altered vision, tingling, numbness, or other discomforts. Consult a doctor before playing video games if you have ever suffered these or similar symptoms, and stop playing immediately and see a doctor if they occur during game play. Parents should monitor their children&rsquo;s video game play for signs of symptoms.</p>
<p>
    MAC APP STORE AND APP STORE PRODUCT MAINTENANCE AND SUPPORT</p>
<p>
    Apple will be responsible for providing any maintenance and support services with respect to the Apple Products only, as specified in the Licensed Application End User License Agreement or the separate end user license agreement, as the case may be, or as required under applicable law. The Application Provider of any Third-Party Product will be solely responsible for providing maintenance and support services with respect to that Product, as specified in the Licensed Application End User License Agreement or the Application Provider end user license agreement, as the case may be, or as required under applicable law.</p>
<p>
    LICENSED APPLICATION END USER LICENSE AGREEMENT</p>
<p>
    The Mac App Store Products,App Store Products and App Store for Apple TV Products (collectively, &ldquo;App Store Product(s)&rdquo;) made available through the Mac App Store Service,App Store Service and App Store for Apple TV Service (collectively, &ldquo;App Store Service(s)&rdquo;) are licensed, not sold, to you. Your license to each App Store Product that you obtain through the App Store Services or associate with your Account is subject to your prior acceptance of this Licensed Application End User License Agreement (&ldquo;Standard EULA&rdquo;), and you agree that the terms of this Standard EULA will apply to each App Store Product that you license through the App Store Service, unless that App Store Product is covered by a valid end user license agreement between you and the Application Provider of that App Store Product, in which case the terms of that separate end user license agreement will govern. Your license to any Apple Product under this Standard EULA or separate end user license agreement is granted by Apple, and your license to any Third-Party Product under this Standard EULA or separate end user license agreement is granted by the Application Provider of that Third-Party Product. Any App Store Product that is subject to the license granted under this Standard EULA is referred to herein as the &ldquo;Licensed Application&rdquo;. The Application Provider or Apple as applicable (&ldquo;Licensor&rdquo;) reserves all rights in and to the Licensed Application not expressly granted to you under this Standard EULA.</p>
<p>
    a. Scope of License: This license granted to you for the Licensed Application by Licensor is limited to a nontransferable license to use the Licensed Application on any Apple-branded products running iOS (including but not limited to iPad, iPhone, and iPod touch) (&ldquo;iOS Devices&rdquo;), Mac OS X (&ldquo;Mac Computers&rdquo;), Apple Watch, and Apple TV, as applicable (collectively, &ldquo;Apple Device(s)&rdquo;) that you own or control and as permitted by the usage rules set forth in the Mac App Store, App Store and iBooks Store Terms and Conditions (the &ldquo;Usage Rules&rdquo;). This license does not allow you to use the Licensed Application on any Apple Device that you do not own or control, and except as provided in the Usage Rules, you may not distribute or make the Licensed Application available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, sell, transfer redistribute, or sublicense the Licensed Application and, if you sell your Apple Device to a third party, you must remove the Licensed Application from the Apple Device before doing so. You may not copy (except as expressly permitted by this license and the Usage Rules), decompile, reverse-engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Licensed Application, any updates, or any part thereof (except as and only to the extent that any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open-sourced components included with the Licensed Application). Any attempt to do so is a violation of the rights of the Licensor and its licensors. If you breach this restriction, you may be subject to prosecution and damages.</p>
<p>
    The terms of this license will govern any upgrades provided by Licensor that replace and/or supplement the original Licensed Application, unless such upgrade is accompanied by a separate license in which case the terms of that license will govern.</p>
<p>
    b. Consent to Use of Data: You agree that Licensor may collect and use technical data and related information&mdash;including but not limited to technical information about your device, system and application software, and peripherals&mdash;that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the Licensed Application. Licensor may use this information, as long as it is in a form that does not personally identify you, to improve its products or to provide services or technologies to you.</p>
<p>
    c. Termination. The license is effective until terminated by you or Licensor. Your rights under this license will terminate automatically without notice from the Licensor if you fail to comply with any term(s) of this license. Upon termination of the license, you shall cease all use of the Licensed Application and destroy all copies, full or partial, of the Licensed Application.</p>
<p>
    d. External Services; Third-Party Materials. The Licensed Application may enable access to Licensor&rsquo;s and/or third-party services and websites (collectively and individually, &quot;External Services&quot;). Use of the External Services requires Internet access and use of certain External Services requires you to accept additional terms. By using this software in connection with an iTunes Store account, you agree to the latest iTunes Store Terms and Conditions and Usage Rules, which you may access and review at <a href="http://www.apple.com/legal/internet-services/itunes/ww/">http://www.apple.com/legal/internet-services/itunes/ww/</a>.</p>
<p>
    You understand that by using any of the External Services, you may encounter content that may be deemed offensive, indecent, or objectionable, which content may or may not be identified as having explicit language, and that the results of any search or entering of a particular URL may automatically and unintentionally generate links or references to objectionable material. Nevertheless, you agree to use the External Services at your sole risk and that neither the Licensor nor its agents shall have any liability to you for content that may be found to be offensive, indecent, or objectionable.</p>
<p>
    Certain External Services may display, include or make available content, data, information, applications or materials from third parties (&ldquo;Third Party Materials&rdquo;) or provide links to certain third party web sites. By using the External Services, you acknowledge and agree that neither the Licensor nor its agents is responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third Party Materials or web sites. Neither the Licensor nor its agents warrant or endorse and does not assume and will not have any liability or responsibility to you or any other person for any third-party services, Third Party Materials or web sites, or for any other materials, products, or services of third parties. Third Party Materials and links to other web sites are provided solely as a convenience to you.</p>
<p>
    Financial information displayed by any External Services is for general informational purposes only and should not be relied upon as investment advice. Before executing any securities transaction based upon information obtained through the External Services, you should consult with a financial or securities professional who is legally qualified to give financial or securities advice in your country or region. Medical information displayed by any App Store Product or External Service is for general information purposes only and should not be relied upon for medical diagnostic or treatment advice except as directed by a doctor. You should consult with a medical professional before relying on medical information available in an App Store Product. Location data provided by any External Services is for basic navigational purposes only and is not intended to be relied upon in situations where precise location information is needed or where erroneous, inaccurate, time-delayed or incomplete location data may lead to death, personal injury, property or environmental damage. Neither the Licensor, nor its agents, nor any of its content providers guarantees the availability, accuracy, completeness, reliability, or timeliness of stock information, location data or any other data displayed by any External Services.</p>
<p>
    You agree that the External Services contain proprietary content, information and material that is owned by Licensor and/or its agents or licensors, and is protected by applicable intellectual property and other laws, including but not limited to copyright, and that you will not use such proprietary content, information or materials in any way whatsoever except for permitted use of the External Services or in any manner that is inconsistent with the terms of this Standard EULA or that infringes any intellectual property rights of a third party or Apple. No portion of the External Services may be reproduced in any form or by any means. You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the External Services, in any manner, and you shall not exploit the External Services in any unauthorized way whatsoever, including but not limited to, using the External Services to transmit any computer viruses, worms, trojan horses or other malware, or by trespass or burdening network capacity. You further agree not to use the External Services in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party, and that neither Licensor nor its agents is in any way responsible for any such use by you, nor for any harassing, threatening, defamatory, offensive, infringing or illegal messages or transmissions that you may receive as a result of using any of the External Services.</p>
<p>
    In addition, External Services and Third Party Materials that may be accessed from, displayed on or linked to from the Apple Devices are not available in all languages or in all countries or regions. Licensor makes no representation that such External Services and Materials are appropriate or available for use in any particular location. To the extent you choose to use or access such External Services and Materials, you do so at your own initiative and are responsible for compliance with any applicable laws, including but not limited to applicable local laws. Licensor reserves the right to change, suspend, remove, or disable access to any External Services at any time without notice. In no event will Licensor be liable for the removal of or disabling of access to any such External Services. Licensor may also impose limits on the use of or access to certain External Services, in any case and without notice or liability.</p>
<p>
    e. NO WARRANTY: YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE LICENSED APPLICATION IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY, AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED APPLICATION AND ANY SERVICES PERFORMED OR PROVIDED BY THE LICENSED APPLICATION ARE PROVIDED &quot;AS IS&quot; AND &ldquo;AS AVAILABLE&rdquo;, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE LICENSED APPLICATION AND ANY SERVICES, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, AND OF NONINFRINGEMENT OF THIRD-PARTY RIGHTS. LICENSOR DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE LICENSED APPLICATION, THAT THE FUNCTIONS CONTAINED IN OR SERVICES PERFORMED OR PROVIDED BY THE LICENSED APPLICATION WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE LICENSED APPLICATION OR SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE LICENSED APPLICATION OR SERVICES WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SHOULD THE LICENSED APPLICATION OR SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.</p>
<p>
    f. Limitation of Liability. TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHALL LICENSOR BE LIABLE FOR PERSONAL INJURY OR ANY INCIDENTAL, SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE LICENSED APPLICATION, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, OR OTHERWISE) AND EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event shall Licensor&rsquo;s total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00). The foregoing limitations will apply even if the above stated remedy fails of its essential purpose.</p>
<p>
    g. You may not use or otherwise export or re-export the Licensed Application except as authorized by United States law and the laws of the jurisdiction in which the Licensed Application was obtained. In particular, but without limitation, the Licensed Application may not be exported or re-exported (a) into any U.S.-embargoed countries or (b) to anyone on the U.S. Treasury Department&#39;s Specially Designated Nationals List or the U.S. Department of Commerce Denied Persons List or Entity List. By using the Licensed Application, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use these products for any purposes prohibited by United States law, including, without limitation, the development, design, manufacture, or production of nuclear, missile, or chemical or biological weapons.</p>
<p>
    h. The Licensed Application and related documentation are &quot;Commercial Items&quot;, as that term is defined at 48 C.F.R. &sect;2.101, consisting of &quot;Commercial Computer Software&quot; and &quot;Commercial Computer Software Documentation&quot;, as such terms are used in 48 C.F.R. &sect;12.212 or 48 C.F.R. &sect;227.7202, as applicable. Consistent with 48 C.F.R. &sect;12.212 or 48 C.F.R. &sect;227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished-rights reserved under the copyright laws of the United States.</p>
<p>
    i. The laws of the State of California, excluding its conflicts of law rules, govern this license and your use of the Licensed Application. Your use of the Licensed Application may also be subject to other local, state, national, or international laws.</p>
<p>
    ADDITIONAL IBOOKS STORE TERMS AND CONDITIONS</p>
<p>
    PURCHASE OF IBOOKS STORE PRODUCTS</p>
<p>
    You acknowledge that you are purchasing the content made available through the iBooks Store Service (the &ldquo;iBooks Store Products&rdquo;) from the third-party provider of that iBooks Store Product (the &ldquo;Publisher&rdquo;); Apple is acting as agent for the Publisher in providing each such iBooks Store Product to you; Apple is not a party to the transaction between you and the Publisher with respect to that iBooks Store Product; and the Publisher of each iBooks Store Product reserves the right to enforce the terms of use relating to that iBooks Store Product. The Publisher of each iBooks Store Product is solely responsible for that iBooks Store Product, the content therein, any warranties to the extent that such warranties have not been disclaimed, and any claims that you or any other party may have relating to that iBooks Store Product or your use of that iBooks Store Product.</p>
<p>
    IBOOKS STORE PRODUCT USAGE RULES</p>
<p>
    (i) You shall be authorized to use the iBooks Store Products only for personal, noncommercial use.</p>
<p>
    (ii) You shall be able to store iBooks Store Products from up to five different Accounts at a time on certain iOS-based devices, such as an iPad, iPod touch, or iPhone.</p>
<p>
    (iii) You shall be able to store iBooks Store Products on five iTunes-authorized devices at any time.</p>
<p>
    (iv) The delivery of iBooks Store Products does not transfer to you any promotional use rights in the iBooks Store Products or any rights to burn the iBooks Store Products to disc.</p>
<p>
    (v) You shall be able to manually sync iBooks Store Products from at least one iTunes-authorized device to devices that have manual sync mode, provided that the iBooks Store Product is associated with an Account on the primary iTunes-authorized device, where the primary iTunes-authorized device is the one that was first synced with the device or the one that you subsequently designate as primary using iTunes.</p>
<p>
    <a name="AM"></a></p>
<p>
    D. APPLE MUSIC TERMS AND CONDITIONS</p>
<p>
    THIS LEGAL AGREEMENT BETWEEN YOU AND APPLE INC. (&quot;APPLE&quot;) GOVERNS YOUR USE OF THE APPLE MUSIC SERVICE AND ANY FEATURES ACCESSIBLE THEREFROM (THE &ldquo;APPLE MUSIC SERVICE&rdquo;).</p>
<p>
    THE APPLE MUSIC SERVICE</p>
<p>
    Apple is the provider of the Apple Music Service, which permits you to access digital music and other content (&ldquo;Apple Music Products&quot;) for end user use only under the terms and conditions set forth in this Agreement.</p>
<p>
    REQUIREMENTS FOR USE OF THE APPLE MUSIC SERVICE</p>
<p>
    The Apple Music Service is only available to individuals aged at least 13 years (or equivalent minimum age based on local law), unless your Apple ID was provided to you as a result of a request by an approved educational institution or established as part of the Family Sharing feature by your parent or guardian. Children under the age of majority should review this Agreement with their parent or guardian to ensure that the child and parent or legal guardian understand it. We do not knowingly collect, use or disclose personal information from children under 13, or equivalent minimum age in the relevant jurisdiction, without verifiable parental consent. Parents and guardians should also remind any minors that conversing with strangers on the Internet can be dangerous and take appropriate precautions to protect children, including monitoring their use of the Apple Music Service.</p>
<p>
    The Apple Music Service is available to you only in the United States, its territories, and possessions. You agree not to use or attempt to use the Apple Music Service from outside these locations. Apple may use technologies to verify your compliance.</p>
<p>
    Use of the Apple Music Service requires a compatible device, Internet access, and certain software; may require periodic updates; and may be affected by the performance of these factors. High-speed Internet access is strongly recommended for regular use and is required for video; access or cellular data fees may apply. Requires iOS 8.4, iTunes 12.2 or Android 4.1 or later. The latest version of required software is recommended and may be required for certain transactions or features. You agree that meeting these requirements, which may change from time to time, is your responsibility.</p>
<p>
    YOUR APPLE MUSIC ACCOUNT</p>
<p>
    As a registered user of the Apple Music Service, you may establish an Account as set forth in, and subject to the terms of, the &ldquo;Your Account&rdquo; paragraph of the iTunes Store Terms and Conditions. In order to use some features of the Apple Music Service, you must enter your Apple ID and password or use Touch ID to authenticate your Account. You agree to provide accurate and complete iTunes Registration Data when you register with, and as you use, the Apple Music Service.</p>
<p>
    Apple logs information about your use of the Apple Music Service. This information includes, but is not limited to, the Apple Music Products you listen to (including whether you skip or stop) and the length of your listening session. Apple may also collect device information such as IP address, device type, operating system version and type, and unique device identifiers. Any music preference information you provide to Apple will also be stored in association with your Account. This information will be used by Apple for purposes such as providing the Apple Music Service, personalizing our recommendations to you, reporting to licensors and paying royalties, customizing and improving Apple products and Services including the Apple Music Service, providing relevant advertising, protecting against fraud and enforcing this Agreement.</p>
<p>
    By using the Apple Music Service, you agree and consent to Apple&rsquo;s and its subsidiaries&rsquo; and agents&rsquo; transmission, collection, maintenance, processing, and use of this information for the aforementioned purposes and as otherwise permitted in accordance with Apple&rsquo;s Privacy Policy, available here: <a href="http://www.apple.com/legal/privacy/">http://www.apple.com/legal/privacy/</a>.</p>
<p>
    APPLE MUSIC SUBSCRIPTION</p>
<p>
    If you buy a subscription to the Apple Music Service (an &ldquo;Apple Music Subscription&rdquo;), Apple will automatically charge the payment method associated with your Apple ID or the payment method associated with your Family Sharing Organizer&rsquo;s account on a recurring basis until you turn off automatic renewal. You may turn off automatic renewal of your Apple Music Subscription at any time in the Account Settings menu on your device or computer, or in the Settings app on your device. If you turn off automatic renewal, you will continue to have access to the Apple Music Service for the remainder of your Apple Music Subscription term. When your Apple Music Subscription term ends, you will lose access to any feature of the Apple Music Service that requires an Apple Music Subscription, including but not limited to access to Apple Music Products accessible through the Apple Music Service or stored on your device, and any songs stored in your iCloud Music Library. Apple Music Subscription purchases are final. Your payment method will be charged no more than 24 hours prior to the expiration of the current Apple Music Subscription period.</p>
<p>
    To be eligible for an Apple Music Subscription at the family rate (where available), you must be enrolled in Family Sharing. If you are a Family Organizer, you agree that Apple will automatically charge your payment method on a recurring basis for any Apple Music Subscription purchases initiated by your Family members until automatic renewal is turned off on the applicable Family member&rsquo;s device or computer.</p>
<p>
    YOU ARE RESPONSIBLE FOR THE TIMELY PAYMENT OF ALL APPLE MUSIC SUBSCRIPTION FEES AND FOR PROVIDING APPLE WITH A VALID PAYMENT METHOD. If Apple is unable to successfully charge your payment method for Apple Music Subscription fees due, Apple reserves the right to cancel your Apple Music Subscription. If your Apple Music Subscription is cancelled, you will lose access to any feature of the Apple Music Service that requires an Apple Music Subscription.</p>
<p>
    If you want to designate a different payment method or if there is a change in your payment method status, you must change your information in the Account Settings menu on your device or computer; this may temporarily disrupt your access to the Apple Music Service while Apple verifies your new payment information.</p>
<p>
    We may contact you via email or push notification regarding your Account or any Apple Music Service feature, for reasons including, without limitation, that your Apple Music Subscription will not automatically renew or will be cancelled.</p>
<p>
    Where available, you may be offered an Apple Music Subscription through your carrier (a &ldquo;Carrier Subscription&rdquo;). If you purchase a Carrier Subscription, your carrier will bill you for the cost of your Apple Music Subscription. Your relationship with the carrier is governed by the carrier&rsquo;s terms and conditions, not this Agreement, and any disputes related to a Carrier Subscription must be directed to your carrier, not Apple. By using the Apple Music Service, you agree that your carrier may exchange your carrier account information, telephone number and subscription information with Apple, and Apple may use this information to determine the status of your Carrier Subscription.</p>
<p>
    ICLOUD MUSIC LIBRARY</p>
<p>
    The iCloud Music Library feature is available to Apple Music subscribers who log in with an Apple ID. iCloud Music Library stores and permits you to remotely access songs and music videos purchased from the iTunes Store and other songs, along with related metadata, playlists, and other information from your other Apple Music-enabled devices. iCloud Music Library is turned on automatically when you set up your Apple Music Subscription. You will be prompted to enable iCloud Music Library when you log in to Apple Music on additional devices. You can enable iCloud Music Library in the Apple Music app settings on your device and in iTunes General Preferences on your computer. You can store up to 25,000 songs in iCloud Music Library. Songs purchased from the iTunes Store do not count against this limit. Songs that do not meet certain criteria or that are not authorized for your device or computer are not eligible for iCloud Music Library. You will not be able to access content stored in your iCloud Music Library when your Apple Music Subscription ends, but you can download songs that were previously acquired from the iTunes Store as set forth in, and subject to the terms of, the &ldquo;Automatic Delivery and Downloading Previous Purchases&rdquo; paragraph of the iTunes Store Terms and Conditions. You hereby agree to use iCloud Music Library only for lawfully acquired content. Any use for illegitimate content infringes the rights of others and may subject you to civil and criminal penalties, including possible monetary damages, for copyright infringement.</p>
<p>
    When you set up your Apple Music Subscription or enable iCloud Music Library, Apple Music will scan the song files on your device or computer and collect other information that may be used to identify media in your Music Library, such as the names of songs, song artists or song durations. iCloud Music Library will use this information to identify songs currently available on Apple Music, and will make identified songs available to you in a format then available on Apple Music. Unidentified songs on your device will remain in local storage, and unidentified songs on your computer are uploaded to iCloud Music Library in the same format or a format determined by Apple. You should backup your Music Library before setting up your Apple Music Subscription or enabling iCloud Music Library. Apple assumes no liability for content that is lost in connection with iCloud Music Library. iCloud Music Library should not be used as backup storage for content. Apple reserves the right to limit types of content uploaded (for example, excessively large files). Identified or uploaded songs and related metadata will be available for access from an Apple Music-compatible device into which you have logged in with your Account and that has been enabled for iCloud Music Library.</p>
<p>
    When you set up your Apple Music Subscription or enable iCloud Music Library, Apple logs information such as the tracks you play, stop or skip, the devices you use, and the time and duration of playback. By using iCloud Music Library, you agree and consent to Apple&rsquo;s and its subsidiaries&rsquo; and agents&rsquo; transmission, collection, maintenance, processing, and use of this information, including your iCloud Music Library usage information, to report to licensors and pay royalties, provide and improve Apple Music features and services and other Apple products and services, and as otherwise permitted in accordance with Apple&rsquo;s Privacy Policy, available here: <a href="http://www.apple.com/legal/privacy/">http://www.apple.com/legal/privacy/</a>.</p>
<p>
    SUBMISSIONS TO THE APPLE MUSIC SERVICE</p>
<p>
    The Apple Music Service may offer interactive features that allow you to submit materials (including but not limited to your name, picture, content, information and third-party content) on areas of the Apple Music Service accessible and viewable by the public. You agree that any use by you of such features, including any materials submitted by you, shall be your sole responsibility, shall not infringe or violate the rights of any other party or violate any laws, contribute to or encourage infringing or otherwise unlawful conduct, or otherwise be obscene, objectionable, or in poor taste. You also agree that you have obtained all necessary rights and licenses applicable to such materials and their distribution. You agree to provide accurate and complete information in connection with your submission of any materials on the Apple Music Service. You hereby grant Apple a worldwide, royalty-free, nonexclusive license to use such materials as part of the Apple Music Service or in relation to Apple Music Products, and the marketing of the Apple Music Service, without any compensation or obligation to you. Apple reserves the right to not post or publish any materials, and to remove or edit any material, at any time in its sole discretion without notice or liability.</p>
<p>
    Apple has the right, but not the obligation, to monitor any materials submitted by you or otherwise available on the Apple Music Service, to investigate any reported or apparent violation of this Agreement, and to take any action that Apple in its sole discretion deems appropriate, including, without limitation, termination hereunder or under Apple&rsquo;s Copyright Policy (<a href="http://www.apple.com/legal/copyright.html">http://www.apple.com/legal/copyright.html</a>).</p>
<p>
    APPLE MUSIC SUBMISSIONS GUIDELINES</p>
<p>
    Content submitted to the Apple Music Service is subject to the following guidelines (the &ldquo;Guidelines&rdquo;), which may be updated from time to time. If you see content submitted to the Apple Music Service that does not comply with these Guidelines, please use the Report a Concern feature.</p>
<p>
    You may not use the Apple Music Service to:</p>
<p>
    - post objectionable, offensive or harmful content, including but not limited to content that is unlawful, harassing, threatening, defamatory, libelous, abusive, violent, obscene, vulgar, invasive of another&rsquo;s privacy, hateful, racially or ethnically offensive, or otherwise objectionable;</p>
<p>
    - post personal, private or confidential information belonging to others, including but not limited to phone numbers, addresses, billing information or photos or videos taken or distributed without the subject&rsquo;s permission;</p>
<p>
    - request personal information from a minor;</p>
<p>
    - impersonate or misrepresent yourself as another person, artist, entity, another Apple Music user, an Apple employee, or a civic or government leader, or otherwise misrepresent your affiliation with a person or entity (Apple reserves the right at any time to reject, reclaim, modify or block any Apple ID, user name, user handle or other identifier which could be deemed to be an impersonation or misrepresentation of your identity, or a misappropriation of another person&#39;s name or identity, or for any other reason at Apple&rsquo;s sole discretion);</p>
<p>
    - engage in copyright or other intellectual property infringement (including posting content that you do not own or have permission to post), or disclose any trade secret or confidential information in violation of a confidentiality, employment, or nondisclosure agreement;</p>
<p>
    - post or transmit spam, including but not limited to unsolicited or unauthorized advertising, promotional materials, or informational announcements;</p>
<p>
    - plan or engage in any illegal activity.</p>
<p>
    CONTENT AVAILABILITY</p>
<p>
    Apple and its licensors reserve the right to change, suspend, remove, discontinue or disable access to the Apple Music Service and any Apple Music Products, content, or other materials comprising a part of the Apple Music Service at any time without notice. In no event will Apple be liable for making these changes. Apple may also impose limits on the use of or access to certain features or portions of the Apple Music Service, in any case and without notice or liability.</p>
<p>
    USE OF CONTENT</p>
<p>
    You agree that the Apple Music Service includes security technology that limits your use of Apple Music Products and that, whether or not Apple Music Products are limited by security technology, you shall use Apple Music Products in compliance with the applicable usage rules established by Apple and its licensors (&ldquo;Apple Music Usage Rules&rdquo;), and that any other use of the Apple Music Products may constitute a copyright infringement. Any security technology is an inseparable part of the Apple Music Products and the Apple Music Service. Apple reserves the right to modify the Apple Music Usage Rules at any time. You agree not to violate, circumvent, reverse-engineer, decompile, disassemble, or otherwise tamper with any of the security technology related to such Apple Music Usage Rules for any reason, or to attempt or assist another person to do so. Apple Music Usage Rules may be controlled and monitored by Apple for compliance purposes, and Apple reserves the right to enforce the Apple Music Usage Rules without notice to you. You agree not to access the Apple Music Service by any means other than through software that is provided by Apple for accessing the Apple Music Service. You shall not access or attempt to access an Account that you are not authorized to access. You agree not to modify the software in any manner or form, or to use modified versions of the software, for any purposes including obtaining unauthorized access to the Apple Music Service. Violations of system or network security may result in civil or criminal liability.</p>
<p>
    APPLE MUSIC USAGE RULES</p>
<p>
    - You shall be authorized to use the Apple Music Service and Apple Music Products only for personal, noncommercial use, except as otherwise authorized by Apple.</p>
<p>
    - You shall be authorized to use the Apple Music Service on ten devices associated with your Account, only five of which can be computers. An individual Apple Music Subscription allows you to stream Apple Music Products to a single device at a time; a family Apple Music Subscription allows you and your Family members to stream Apple Music Products to up to six devices at a time.</p>
<p>
    - You shall not be entitled to burn Apple Music Products.</p>
<p>
    - The delivery of the Apple Music Service or Apple Music Products does not transfer to you any commercial or promotional use rights in the Apple Music Service or Apple Music Products.</p>
<p>
    THIRD-PARTY MATERIALS</p>
<p>
    Certain Apple Music Products, content, and services available via the Apple Music Service may include materials from third parties. Apple may provide links to third-party websites, products or services as a convenience to you. You agree that Apple is not responsible for examining or evaluating the content or accuracy and Apple does not warrant and will not have any liability or responsibility for any third-party materials, websites, products or services. You agree that you will not use any third-party materials in a manner that would infringe or violate the rights of any other party and that Apple is not in any way responsible for any such use by you.</p>
<p>
    OBJECTIONABLE MATERIAL</p>
<p>
    You understand that by using the Apple Music Service, you may encounter material that you may deem to be offensive, indecent, or objectionable, and that such content may or may not be identified as having explicit material. You agree to use the Apple Music Service at your sole risk and Apple shall have no liability to you for material that may be found to be offensive, indecent, or objectionable. Apple Music Product types and descriptions are provided for convenience, and you agree that Apple does not guarantee their accuracy.</p>
<p>
    INTELLECTUAL PROPERTY</p>
<p>
    You agree that the Apple Music Service, including but not limited to Apple Music Products, graphics, user interface, audio, video, editorial content, and the scripts and software used to implement the Apple Music Service, contains proprietary information and material that is owned by Apple and/or its licensors, and is protected by applicable intellectual property and other laws, including but not limited to copyright. You agree that you will not use such proprietary information or materials in any way whatsoever except for use of the Apple Music Service in compliance with this Agreement. No portion of the Apple Music Service may be reproduced in any form or by any means, except as expressly permitted in these terms. You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the Apple Music Service in any manner, and you shall not exploit the Apple Music Service in any unauthorized way whatsoever, including, but not limited to, by trespass or burdening network capacity.</p>
<p>
    All copyrights in and to the Apple Music Service (including the compilation of content, postings, links to other Internet resources, and descriptions of those resources) and related software are owned by Apple and/or its licensors, who reserve all their rights in law and equity. THE USE OF THE SOFTWARE OR ANY PART OF THE APPLE MUSIC SERVICE, EXCEPT FOR USE OF THE APPLE MUSIC SERVICE AS PERMITTED IN THIS AGREEMENT, IS STRICTLY PROHIBITED AND INFRINGES ON THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS AND MAY SUBJECT YOU TO CIVIL AND CRIMINAL PENALTIES, INCLUDING POSSIBLE MONETARY DAMAGES, FOR COPYRIGHT INFRINGEMENT.</p>
<p>
    As user of the Apple Music Service in good standing, you may be provided with limited access to download certain album cover art for music stored on a device. Such access is provided as an accommodation only, and Apple does not warrant, and will not have any liability or responsibility for, such album cover art or your use thereof. You may access album cover art only in connection with the Apple Music Service. Album cover art is provided for personal, noncommercial use only. You agree that you will not use album cover art in any manner that would infringe or violate this Agreement or the rights of any other party, and that Apple is not in any way responsible for any such use by you.</p>
<p>
    TERMINATION</p>
<p>
    If you fail, or Apple suspects that you have failed, to comply with any of the provisions of this Agreement, Apple, at its sole discretion, without notice to you, and without waiving your liability for all amounts due under your Account, may: (i) terminate this Agreement and/or your Account; and/or (ii) terminate the license to the software; and/or (iii) preclude access to the Apple Music Service (or any part thereof).</p>
<p>
    DISCLAIMER OF WARRANTIES; LIABILITY LIMITATION</p>
<p>
    APPLE DOES NOT GUARANTEE, REPRESENT, OR WARRANT THAT YOUR USE OF THE APPLE MUSIC SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, AND YOU AGREE THAT FROM TIME TO TIME APPLE MAY REMOVE THE APPLE MUSIC SERVICE FOR INDEFINITE PERIODS OF TIME, OR CANCEL THE APPLE MUSIC SERVICE AT ANY TIME, WITHOUT NOTICE TO YOU.</p>
<p>
    YOU EXPRESSLY AGREE THAT YOUR USE OF, OR INABILITY TO USE, THE APPLE MUSIC SERVICE IS AT YOUR SOLE RISK. THE APPLE MUSIC SERVICE AND ALL PRODUCTS AND SERVICES DELIVERED TO YOU THROUGH THE APPLE MUSIC SERVICE ARE (EXCEPT AS EXPRESSLY STATED BY APPLE) PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; FOR YOUR USE, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, THE ABOVE EXCLUSION OF IMPLIED WARRANTIES MAY NOT APPLY TO YOU.</p>
<p>
    IN NO CASE SHALL APPLE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE APPLE MUSIC SERVICE OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR USE OF THE APPLE MUSIC SERVICE, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR OMISSIONS IN ANY CONTENT OR APPLE MUSIC PRODUCTS, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT OR APPLE MUSIC PRODUCTS POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE APPLE MUSIC SERVICE, EVEN IF ADVISED OF THEIR POSSIBILITY. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, APPLE&#39;S LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
<p>
    APPLE SHALL USE REASONABLE EFFORTS TO PROTECT INFORMATION SUBMITTED BY YOU IN CONNECTION WITH THE APPLE MUSIC SERVICE, BUT YOU AGREE THAT YOUR SUBMISSION OF SUCH INFORMATION IS AT YOUR SOLE RISK, AND APPLE HEREBY DISCLAIMS ANY AND ALL LIABILITY TO YOU FOR ANY LOSS OR LIABILITY RELATING TO SUCH INFORMATION IN ANY WAY.</p>
<p>
    APPLE DOES NOT REPRESENT OR GUARANTEE THAT THE APPLE MUSIC SERVICE WILL BE FREE FROM LOSS, CORRUPTION, ATTACK, VIRUSES, INTERFERENCE, HACKING, OR OTHER SECURITY INTRUSION, AND APPLE DISCLAIMS ANY LIABILITY RELATING THERETO. YOU SHALL BE RESPONSIBLE FOR BACKING UP YOUR OWN SYSTEM BEFORE, DURING AND AFTER USING THE APPLE MUSIC SERVICE, INCLUDING ANY CONTENT OR DATA USED IN CONNECTION WITH OR ACQUIRED FROM THE APPLE MUSIC SERVICE.</p>
<p>
    WAIVER AND INDEMNITY</p>
<p>
    BY USING THE APPLE MUSIC SERVICE, YOU AGREE, TO THE EXTENT PERMITTED BY LAW, TO INDEMNIFY AND HOLD APPLE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, AND LICENSORS HARMLESS WITH RESPECT TO ANY CLAIMS ARISING OUT OF YOUR BREACH OF THIS AGREEMENT, YOUR USE OF THE APPLE MUSIC SERVICE, OR ANY ACTION TAKEN BY APPLE AS PART OF ITS INVESTIGATION OF A SUSPECTED VIOLATION OF THIS AGREEMENT OR AS A RESULT OF ITS FINDING OR DECISION THAT A VIOLATION OF THIS AGREEMENT HAS OCCURRED. THIS MEANS THAT YOU CANNOT SUE OR RECOVER ANY DAMAGES FROM APPLE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, AND LICENSORS AS A RESULT OF ITS DECISION TO REMOVE OR REFUSE TO PROCESS ANY INFORMATION OR CONTENT, TO WARN YOU, TO SUSPEND OR TERMINATE YOUR ACCESS TO THE APPLE MUSIC SERVICE, OR TO TAKE ANY OTHER ACTION DURING THE INVESTIGATION OF A SUSPECTED VIOLATION OR AS A RESULT OF APPLE&#39;S CONCLUSION THAT A VIOLATION OF THIS AGREEMENT HAS OCCURRED. THIS WAIVER AND INDEMNITY PROVISION APPLIES TO ALL VIOLATIONS DESCRIBED IN OR CONTEMPLATED BY THIS AGREEMENT.</p>
<p>
    CHANGES</p>
<p>
    Apple reserves the right at any time to modify this Agreement and to impose new or additional terms or conditions on your use of the Apple Music Service. Such modifications and additional terms and conditions will be effective immediately and incorporated into this Agreement. Your continued use of the Apple Music Service will be deemed acceptance thereof.</p>
<p>
    COPYRIGHT NOTICE</p>
<p>
    If you believe that any Apple Music Products or any other content available through the Apple Music Service infringes a copyright claimed by you, please contact Apple&#39;s Copyright Agent as described in our Copyright Policy at <a href="http://www.apple.com/legal/trademark/claimsofcopyright.html">http://www.apple.com/legal/trademark/claimsofcopyright.html</a>. Apple may, in its sole discretion, suspend and/or terminate Accounts of users that are found to be repeat infringers.</p>
<p>
    MISCELLANEOUS</p>
<p>
    This Agreement constitutes the entire agreement between you and Apple and governs your use of the Apple Music Service, superseding any prior agreements between you and Apple. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third-party content, or third-party software. If any part of this Agreement is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect. Apple&#39;s failure to enforce any right or provisions in this Agreement will not constitute a waiver of such or any other provision. Apple will not be responsible for failures to fulfill any obligations due to causes beyond its control.</p>
<p>
    The Apple Music Service is operated by Apple from its offices in the United States. You agree to comply with all local, state, federal, and national laws, statutes, ordinances, and regulations that apply to your use of the Apple Music Service. All transactions on the Apple Music Service are governed by California law, without giving effect to its conflict of law provisions. Your use of the Apple Music Service may also be subject to other laws. You expressly agree that exclusive jurisdiction for any claim or dispute with Apple or relating in any way to your use of the Apple Music Service resides in the courts in the State of California. Risk of loss and title for all electronically delivered transactions pass to the purchaser in California upon electronic transmission to the recipient. No Apple employee or agent has the authority to vary this Agreement.</p>
<p>
    Apple may notify you with respect to the Apple Music Service by sending you an email message, or a letter via postal mail to your Account mailing address, or by a posting on the Apple Music Service. Notices shall become effective immediately.</p>
<p>
    Apple reserves the right to take steps Apple believes are reasonably necessary or appropriate to enforce and/or verify compliance with any part of this Agreement. You agree that Apple has the right, without liability to you, to disclose any Account information to law enforcement authorities, government officials, and/or a third party, as Apple believes is reasonably necessary or appropriate to enforce and/or verify compliance with any part of this Agreement (including but not limited to Apple&#39;s right to cooperate with any legal process relating to your use of the Apple Music Service and/or Apple Music Products, and/or a third-party claim that your use of the Apple Music Service and/or Apple Music Products is unlawful and/or infringes such third party&#39;s rights).</p>
<p>
    Last Updated: October 21, 2015</p>
        </div>
    </div>
	</body>
	</html>
	