DROP TABLE IF EXISTS "iata_tp" CASCADE;
DROP TABLE IF EXISTS "iata_cities" CASCADE;
DROP TABLE IF EXISTS "iata_states" CASCADE;
DROP TABLE IF EXISTS "iata_countries" CASCADE;
DROP TABLE IF EXISTS "iata_carriers" CASCADE;

DROP TABLE IF EXISTS "travel_comments" CASCADE;
DROP TABLE IF EXISTS "travels" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "expirable_storage" CASCADE;

DROP FUNCTION IF EXISTS process_updated_column() CASCADE;
