---
- hosts: localhost
  become: yes
  roles:
    - role: application
      env: 'dev'
      nginx_root: '/vagrant/public'
    - role: database
      addresses: '*'
      hba_entries: ["host all all 0.0.0.0/0 md5"]
      databases: [api_dev, api_test]
      users:
        - name: api_dev
          password: api_dev
          db: api_dev
          roles: "LOGIN"
        - name: api_test
          password: api_test
          db: api_test
          roles: "LOGIN,CREATEDB,SUPERUSER"
      scripts:
        - db: api_dev
          file: /vagrant/db/main/ext/postgis.sql
        - db: api_test
          file: /vagrant/db/main/ext/postgis.sql

  tasks:

  - name: Install packages
    apt: name={{ item }}
    with_items:
      - vim
      - mc
      - unzip
      - htop

  - include: tasks/apt_autoremove.yml
  - include: tasks/install_composer.yml
  - include: tasks/update_composer.yml

  - name: run migrations
    shell: APP_ENV=dev bin/db.php migrations:migrate --no-interaction
    args:
      chdir: /vagrant
