---
- hosts: self
  sudo: yes

  vars:
    php_sapi: [cli, fpm]

  tasks:

  - apt_repository: repo='{{ item }}' state=present
    with_items:
      - 'deb http://packages.dotdeb.org jessie all'
      - 'deb http://apt.postgresql.org/pub/repos/apt jessie-pgdg main'

  - apt_key: url={{ item }} state=present
    with_items:
      -  'https://www.dotdeb.org/dotdeb.gpg'
      -  'https://www.postgresql.org/media/keys/ACCC4CF8.asc'

  - apt: upgrade=dist update_cache=yes

  - name: Remove php5
    apt: name=php5-common state=absent purge=yes

  - name: Install packages
    apt: name={{ item }} state=present
    with_items:
      - php7.0-common
      - php7.0-dev
      - php7.0-cli
      - php7.0-fpm
      - php7.0-curl
      - php7.0-pgsql
      - php7.0-xdebug
      - postgresql-9.5
      - postgresql-contrib-9.5
      - postgresql-9.5-postgis-2.2
      - curl
      - nginx
      - git
      - python-psycopg2


  - name: Create DB api_dev
    sudo_user: postgres
    postgresql_db: name=api_dev

  - name: Create DB api_dev
    sudo_user: postgres
    shell: psql api_dev -f /vagrant/db/ext/postgis.sql

  - name: Setup DB admin user
    sudo_user: postgres
    postgresql_user: name=postgres password=postgres

  - name: Setup DB api_dev user
    sudo_user: postgres
    postgresql_user: name=api_dev db=api_dev password=api_dev role_attr_flags=LOGIN

  - name: PostgreSQL api_test user setup
    sudo_user: postgres
    postgresql_user: name=api_test password=api_test role_attr_flags=LOGIN,CREATEDB,SUPERUSER

  - name: Open access to PostgreSQL
    lineinfile: dest=/etc/postgresql/9.5/main/pg_hba.conf line="host all all 0.0.0.0/0 md5" state=present
    notify:
      - restart postgresql

  - name: Configure php.ini
    template: src=conf/php/vm.ini dest=/etc/php/7.0/{{ item }}/conf.d/99-vm.ini
    with_items: php_sapi
    notify:
      - restart php7.0-fpm
      - restart nginx

  - name: Configure nginx
    template: src=conf/nginx/vm dest=/etc/nginx/sites-available/default
    notify:
      - restart php7.0-fpm
      - restart nginx

  - name: Install composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    args:
      creates: /usr/local/bin/composer

  - name: Update composer
    shell: composer self-update
    register: composer_update
    changed_when: "'Updating to version' in composer_update.stdout"

  - name: Run migrations
    shell: APP_ENV=dev /vagrant/bin/db.php up

  handlers:
    - name: restart php7.0-fpm
      service: name=php7.0-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart postgresql
      service: name=postgresql state=restarted
